title: Alex Kobayashi # your name (or website title) here
logo: "/images/photo_avatar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master's Student in Hydraulics and Sanitation from University of São Paulo .
  <br><br>
  Python programmer and data science enthusiast.
  <br><br>
  <a href="https://www.linkedin.com/in/alex-kobayashi-05a615182/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
